<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Offer;

class OfferSeeder extends Seeder
{
    public function run(): void
    {
        Offer::insert([
            [
                'general_status' => 'Angebot',
                'general_offer_number' => 'O-2025001',
                'general_profile_description' => 101,
                'general_creation_date' => '2025-03-28 10:00:00',
                'general_created_by_user_id' => 1,
                'general_color' => 'Silber',
                'general_packaging' => 5,
                'general_tool_number' => 'T-12345',
                'general_order_number' => 'OR-98765',
                'general_delivery_type' => 'frei',
                'general_article_number' => 'A-0001',
                'general_customer' => 'Kunde A',
                'general_customer_contact_person' => 'Max Mustermann',
                'general_customer_article_number' => 'CA-1001',
                'general_request_date' => '2025-04-01',
                'general_request_number' => 1001,
                'general_raw_material_price_total_overwritten' => 1500.50,
                'general_raw_material_purchase_discount' => 5.0,
                'general_comments' => 'Erstangebot für Kunde A',

                // Calculation
                'calculation_quantityA' => 1000,
                'calculation_quantityB' => 2000,
                'calculation_quantityC' => 3000,
                'calculation_quantityD' => 4000,
                'calculation_quantityE' => 5000,
                'calculation_processing_lfm_hourly_rate' => 45.5,
                'calculation_processing_piece_hourly_rate' => 30.0,
                'calculation_processing_lfm_runtime' => 12.5,
                'calculation_processing_piece_runtime' => 8.0,
                'calculation_processing_lfm_runtime_factor' => 2,
                'calculation_processing_piece_runtime_factor' => 3,
                'calculation_processing_lfm_packing_time' => 1.5,
                'calculation_processing_piece_packing_time' => 1.2,
                'calculation_processing_lfm_packing_time_factor' => 1,
                'calculation_processing_piece_packing_time_factor' => 2,
                'calculation_additional_setup_time' => 10,
                'calculation_additional_hourly_rate' => 50.0,
                'calculation_additional_transport_costs_total' => 200.0,
                'calculation_additional_box_count' => 10,
                'calculation_additional_box_price_per_piece' => 5.0,
                'calculation_additional_box_price_flat_additional' => 20.0,
                'calculation_additional_single_print' => 2.5,
                'calculation_additional_single_print_price' => 1.5,
                'calculation_working_setup_quantity_relative' => 500,
                'calculation_working_setup_quantity_additional' => 222,
                'calculation_working_extrusion_speed' => 15.0,
                'calculation_working_annual_requirement_estimated' => 20000,
                'calculation_working_tool_costs_total' => 10000.0,
                'calculation_working_tool_costs_customer' => 5000.0,
                'calculation_working_tool_costs_amortization_years' => 5,
                'calculation_working_allocation_costs_additional' => 3,
                'calculation_working_profile_cross_section' => 25.0,
                'calculation_working_profile_cross_section_deviation_lower' => 0,
                'calculation_working_profile_cross_section_deviation_upper' => 0,
                'calculation_working_setup_quantity_total' => 50,
                'calculation_working_hourly_rate' => 60,
                'calculation_working_additional_costs' => 100.0,
                'calculation_working_commission' => 5.0,
                'calculation_working_profit' => 15.0,
                'calculation_working_discount' => 3.0,

                // Pricing
                'pricing_grad_qtyB_add_hourlyrate' => 10.0,
                'pricing_grad_qtyC_add_hourlyrate' => 20.0,
                'pricing_grad_qtyD_add_hourlyrate' => 30.0,
                'pricing_grad_qtyE_add_hourlyrate' => 40.0,
                'pricing_grad_qtyB_add_setupcosts' => 50.0,
                'pricing_grad_qtyC_add_setupcosts' => 60.0,
                'pricing_grad_qtyD_add_setupcosts' => 70.0,
                'pricing_grad_qtyE_add_setupcosts' => 80.0,
                'pricing_grad_qtyB_add_transport' => 90.0,
                'pricing_grad_qtyC_add_transport' => 100.0,
                'pricing_grad_qtyD_add_transport' => 110.0,
                'pricing_grad_qtyE_add_transport' => 120.0,

                // Runningcard
                'runningcard_sampling_date' => '2025-04-05',
                'runningcard_sampling_quantity' => 100,
                'runningcard_sampling_length' => 500,
                'runningcard_sampling_packing' => 10,
                'runningcard_sampling_indication' => 'Good quality',
                'runningcard_qualitity_indication' => 'No defects found during inspection.',
                'runningcard_printing' => 'Standard black ink printing.',
                'runningcard_packing_type' => 'Box',
                'runningcard_packing_variant' => 'Type A',
                'runningcard_packing_length' => 120,
                'runningcard_packing_packing_unit' => 5,
                'runningcard_packing_quantity' => 500,
                'runningcard_packing_description' => 'Packed in standard boxes of 5 units.',
                'runningcard_hourlyrecording_construction' => 2,
                'runningcard_hourlyrecording_toolwork' => 3,
                'runningcard_hourlyrecording_entry' => 1,
                'runningcard_hourlyrecording_entrystitches' => 50,
                'runningcard_hourlyrecording_entrydriver_user_id' => 1,
                'runningcard_hourlyrecording_toolmaker_user_id' => 1,
                'runningcard_tool_costs' => 1000,
                'runningcard_tool_cost_type' => 'Purchase',
                'runningcard_tool_hint' => 'Tool must be recalibrated annually.',
            ],
            [
                'general_status' => 'Auftrag',
                'general_offer_number' => 'O-2025002',
                'general_profile_description' => 102,
                'general_creation_date' => '2025-03-28 11:00:00',
                'general_created_by_user_id' => 2,
                'general_color' => 'Blau',
                'general_packaging' => 3,
                'general_tool_number' => 'T-67890',
                'general_order_number' => 'OR-54321',
                'general_delivery_type' => 'unfrei',
                'general_article_number' => 'A-0002',
                'general_customer' => 'Kunde B',
                'general_customer_contact_person' => 'Erika Beispiel',
                'general_customer_article_number' => 'CA-2002',
                'general_request_date' => '2025-04-05',
                'general_request_number' => 1002,
                'general_raw_material_price_total_overwritten' => 1750.00,
                'general_raw_material_purchase_discount' => 7.5,
                'general_comments' => 'Sonderanfertigung für Kunde B',

                // Calculation
                'calculation_quantityA' => 1500,
                'calculation_quantityB' => 2500,
                'calculation_quantityC' => 3500,
                'calculation_quantityD' => 4500,
                'calculation_quantityE' => 5500,
                'calculation_processing_lfm_hourly_rate' => 50.0,
                'calculation_processing_piece_hourly_rate' => 35.0,
                'calculation_processing_lfm_runtime' => 14.0,
                'calculation_processing_piece_runtime' => 9.0,
                'calculation_processing_lfm_runtime_factor' => 3,
                'calculation_processing_piece_runtime_factor' => 4,
                'calculation_processing_lfm_packing_time' => 2.0,
                'calculation_processing_piece_packing_time' => 1.8,
                'calculation_processing_lfm_packing_time_factor' => 2,
                'calculation_processing_piece_packing_time_factor' => 3,
                'calculation_additional_setup_time' => 12,
                'calculation_additional_hourly_rate' => 55.0,
                'calculation_additional_transport_costs_total' => 220.0,
                'calculation_additional_box_count' => 12,
                'calculation_additional_box_price_per_piece' => 6.0,
                'calculation_additional_box_price_flat_additional' => 22.0,
                'calculation_additional_single_print' => 3.0,
                'calculation_additional_single_print_price' => 2.0,
                'calculation_working_setup_quantity_relative' => 600,
                'calculation_working_setup_quantity_additional' => 222,
                'calculation_working_extrusion_speed' => 14.5,
                'calculation_working_annual_requirement_estimated' => 25000,
                'calculation_working_tool_costs_total' => 12000.0,
                'calculation_working_tool_costs_customer' => 6000.0,
                'calculation_working_tool_costs_amortization_years' => 6,
                'calculation_working_allocation_costs_additional' => 4,
                'calculation_working_profile_cross_section' => 27.0,
                'calculation_working_profile_cross_section_deviation_lower' => 0,
                'calculation_working_profile_cross_section_deviation_upper' => 0,
                'calculation_working_setup_quantity_total' => 55,
                'calculation_working_hourly_rate' => 65,
                'calculation_working_additional_costs' => 120.0,
                'calculation_working_commission' => 6.0,
                'calculation_working_profit' => 18.0,
                'calculation_working_discount' => 4.0,

                // Pricing
                'pricing_grad_qtyB_add_hourlyrate' => 15.0,
                'pricing_grad_qtyC_add_hourlyrate' => 25.0,
                'pricing_grad_qtyD_add_hourlyrate' => 35.0,
                'pricing_grad_qtyE_add_hourlyrate' => 45.0,
                'pricing_grad_qtyB_add_setupcosts' => 55.0,
                'pricing_grad_qtyC_add_setupcosts' => 65.0,
                'pricing_grad_qtyD_add_setupcosts' => 75.0,
                'pricing_grad_qtyE_add_setupcosts' => 85.0,
                'pricing_grad_qtyB_add_transport' => 95.0,
                'pricing_grad_qtyC_add_transport' => 105.0,
                'pricing_grad_qtyD_add_transport' => 115.0,
                'pricing_grad_qtyE_add_transport' => 125.0,

                // Runningcard
                'runningcard_sampling_date' => '2025-04-07',
                'runningcard_sampling_quantity' => 120,
                'runningcard_sampling_length' => 520,
                'runningcard_sampling_packing' => 12,
                'runningcard_sampling_indication' => 'Minor defects',
                'runningcard_qualitity_indication' => 'Few scratches detected.',
                'runningcard_printing' => 'Custom color printing.',
                'runningcard_packing_type' => 'Crate',
                'runningcard_packing_variant' => 'Type B',
                'runningcard_packing_length' => 130,
                'runningcard_packing_packing_unit' => 6,
                'runningcard_packing_quantity' => 600,
                'runningcard_packing_description' => 'Packed in wooden crates, 6 per unit.',
                'runningcard_hourlyrecording_construction' => 3,
                'runningcard_hourlyrecording_toolwork' => 2,
                'runningcard_hourlyrecording_entry' => 2,
                'runningcard_hourlyrecording_entrystitches' => 60,
                'runningcard_hourlyrecording_entrydriver_user_id' => 2,
                'runningcard_hourlyrecording_toolmaker_user_id' => 2,
                'runningcard_tool_costs' => 1200,
                'runningcard_tool_cost_type' => 'Rental',
                'runningcard_tool_hint' => 'Rental expires end of year.',
            ],
            [
                'general_status' => 'Produziert',
                'general_offer_number' => 'O-2025003',
                'general_profile_description' => 103,
                'general_creation_date' => '2025-03-28 12:00:00',
                'general_created_by_user_id' => 3,
                'general_color' => 'Schwarz',
                'general_packaging' => 4,
                'general_tool_number' => 'T-11223',
                'general_order_number' => 'OR-33445',
                'general_delivery_type' => 'frei',
                'general_article_number' => 'A-0003',
                'general_customer' => 'Kunde C',
                'general_customer_contact_person' => 'Hans Beispiel',
                'general_customer_article_number' => 'CA-3003',
                'general_request_date' => '2025-04-10',
                'general_request_number' => 1003,
                'general_raw_material_price_total_overwritten' => 2000.75,
                'general_raw_material_purchase_discount' => 6.0,
                'general_comments' => 'Produktionsauftrag für Kunde C',

                // Calculation
                'calculation_quantityA' => 2000,
                'calculation_quantityB' => 3000,
                'calculation_quantityC' => 4000,
                'calculation_quantityD' => 5000,
                'calculation_quantityE' => 6000,
                'calculation_processing_lfm_hourly_rate' => 55.5,
                'calculation_processing_piece_hourly_rate' => 40.0,
                'calculation_processing_lfm_runtime' => 16.0,
                'calculation_processing_piece_runtime' => 10.0,
                'calculation_processing_lfm_runtime_factor' => 4,
                'calculation_processing_piece_runtime_factor' => 5,
                'calculation_processing_lfm_packing_time' => 2.5,
                'calculation_processing_piece_packing_time' => 2.2,
                'calculation_processing_lfm_packing_time_factor' => 3,
                'calculation_processing_piece_packing_time_factor' => 4,
                'calculation_additional_setup_time' => 14,
                'calculation_additional_hourly_rate' => 60.0,
                'calculation_additional_transport_costs_total' => 250.0,
                'calculation_additional_box_count' => 15,
                'calculation_additional_box_price_per_piece' => 7.0,
                'calculation_additional_box_price_flat_additional' => 25.0,
                'calculation_additional_single_print' => 3.5,
                'calculation_additional_single_print_price' => 2.5,
                'calculation_working_setup_quantity_relative' => 700,
                'calculation_working_setup_quantity_additional' => 222,
                'calculation_working_extrusion_speed' => 14.0,
                'calculation_working_annual_requirement_estimated' => 30000,
                'calculation_working_tool_costs_total' => 15000.0,
                'calculation_working_tool_costs_customer' => 7000.0,
                'calculation_working_tool_costs_amortization_years' => 7,
                'calculation_working_allocation_costs_additional' => 5,
                'calculation_working_profile_cross_section' => 30.0,
                'calculation_working_profile_cross_section_deviation_lower' => 0,
                'calculation_working_profile_cross_section_deviation_upper' => 0,
                'calculation_working_setup_quantity_total' => 60,
                'calculation_working_hourly_rate' => 70,
                'calculation_working_additional_costs' => 140.0,
                'calculation_working_commission' => 7.0,
                'calculation_working_profit' => 20.0,
                'calculation_working_discount' => 5.0,

                // Pricing
                'pricing_grad_qtyB_add_hourlyrate' => 20.0,
                'pricing_grad_qtyC_add_hourlyrate' => 30.0,
                'pricing_grad_qtyD_add_hourlyrate' => 40.0,
                'pricing_grad_qtyE_add_hourlyrate' => 50.0,
                'pricing_grad_qtyB_add_setupcosts' => 60.0,
                'pricing_grad_qtyC_add_setupcosts' => 70.0,
                'pricing_grad_qtyD_add_setupcosts' => 80.0,
                'pricing_grad_qtyE_add_setupcosts' => 90.0,
                'pricing_grad_qtyB_add_transport' => 100.0,
                'pricing_grad_qtyC_add_transport' => 110.0,
                'pricing_grad_qtyD_add_transport' => 120.0,
                'pricing_grad_qtyE_add_transport' => 130.0,

                // Runningcard
                'runningcard_sampling_date' => '2025-04-12',
                'runningcard_sampling_quantity' => 150,
                'runningcard_sampling_length' => 550,
                'runningcard_sampling_packing' => 15,
                'runningcard_sampling_indication' => 'Excellent',
                'runningcard_qualitity_indication' => 'Perfect sample, no issues.',
                'runningcard_printing' => 'UV-resistant printing.',
                'runningcard_packing_type' => 'Pallet',
                'runningcard_packing_variant' => 'Type C',
                'runningcard_packing_length' => 140,
                'runningcard_packing_packing_unit' => 7,
                'runningcard_packing_quantity' => 700,
                'runningcard_packing_description' => 'Packed on pallets, 7 units each.',
                'runningcard_hourlyrecording_construction' => 4,
                'runningcard_hourlyrecording_toolwork' => 5,
                'runningcard_hourlyrecording_entry' => 3,
                'runningcard_hourlyrecording_entrystitches' => 80,
                'runningcard_hourlyrecording_entrydriver_user_id' => 3,
                'runningcard_hourlyrecording_toolmaker_user_id' => 3,
                'runningcard_tool_costs' => 1500,
                'runningcard_tool_cost_type' => 'Lease',
                'runningcard_tool_hint' => 'Leased tool, return after project completion.',
            ],
        ]);
    }
}
