import { OfferTableModel } from "@interfaces/Offer.model";
import { Column } from "@types/Table";

export const OfferColumns: Column<OfferTableModel>[] = [
  { label: "Angebotsnummer", render: (row) => row.angebotsnummer },
  { label: "Auftraggeber", render: (row) => row.auftraggeber },
  { label: "Profilbezeichnung", render: (row) => row.profilbezeichnung },
  { label: "Erstelldatum", render: (row) => row.erstelldatum },
];

export const tableData = [
  {
    id: 1,
    angebotsnummer: "2025-001",
    auftraggeber: "stroud@gmail.com",
    profilbezeichnung: "Verbindungsprofil",
    erstelldatum: "vor 45 Minuten",
  },
  {
    id: 2,
    angebotsnummer: "2025-001.1",
    auftraggeber: "fields@gmail.com",
    profilbezeichnung: "lorem ipsum",
    erstelldatum: "vor 30 Minuten",
  },
  {
    id: 3,
    angebotsnummer: "2025-001.2",
    auftraggeber: "troiani@gmail.com",
    profilbezeichnung: "dolor est",
    erstelldatum: "vor 2 Minuten",
  },
  {
    id: 4,
    angebotsnummer: "2024-045",
    auftraggeber: "moore@gmail.com",
    profilbezeichnung: "Verbindungsprofil",
    erstelldatum: "20.07.2024",
  },
  {
    id: 5,
    angebotsnummer: "2024-120.1",
    auftraggeber: "dermot@gmail.com",
    profilbezeichnung: "Verbindungsprofil",
    erstelldatum: "15.04.2024",
  },
  {
    id: 6,
    angebotsnummer: "2025-012",
    auftraggeber: "doe@gmail.com",
    profilbezeichnung: "repetuum",
    erstelldatum: "04.01.2025",
  },
  {
    id: 7,
    angebotsnummer: "2025-016",
    auftraggeber: "merces@gmail.com",
    profilbezeichnung: "lorem ipsum",
    erstelldatum: "10.01.2025",
  },
  {
    id: 8,
    angebotsnummer: "2025-016.1",
    auftraggeber: "ferdinand@gmail.com",
    profilbezeichnung: "Verbindungsprofil",
    erstelldatum: "12.01.2025",
  },
  {
    id: 9,
    angebotsnummer: "2024-025",
    auftraggeber: "williams@gmail.com",
    profilbezeichnung: "dimi et fasum",
    erstelldatum: "16.09.2024",
  },
  {
    id: 10,
    angebotsnummer: "2024-012",
    auftraggeber: "ricci@gmail.com",
    profilbezeichnung: "Verbindungsprofil",
    erstelldatum: "24.08.2024",
  },
  {
    id: 11,
    angebotsnummer: "2024-014",
    auftraggeber: "smith@gmail.com",
    profilbezeichnung: "lorem ipsum",
    erstelldatum: "11.06.2024",
  },
  {
    id: 12,
    angebotsnummer: "2024-004",
    auftraggeber: "sherman@gmail.com",
    profilbezeichnung: "Mater et cook",
    erstelldatum: "04.05.2024",
  },
  {
    id: 13,
    angebotsnummer: "2025-003",
    auftraggeber: "gonzalez@gmail.com",
    profilbezeichnung: "Verbindungsprofil",
    erstelldatum: "01.01.2025",
  },
  {
    id: 14,
    angebotsnummer: "2025-020",
    auftraggeber: "anderson@gmail.com",
    profilbezeichnung: "dolorum sit",
    erstelldatum: "02.02.2025",
  },
  {
    id: 15,
    angebotsnummer: "2025-021",
    auftraggeber: "lee@gmail.com",
    profilbezeichnung: "network profile",
    erstelldatum: "03.03.2025",
  },
  {
    id: 16,
    angebotsnummer: "2025-022",
    auftraggeber: "kumar@gmail.com",
    profilbezeichnung: "ipsum vitae",
    erstelldatum: "04.04.2025",
  },
  {
    id: 17,
    angebotsnummer: "2025-023",
    auftraggeber: "brown@gmail.com",
    profilbezeichnung: "Verbindungsprofil",
    erstelldatum: "05.05.2025",
  },
  {
    id: 18,
    angebotsnummer: "2025-024",
    auftraggeber: "zhang@gmail.com",
    profilbezeichnung: "dolor net",
    erstelldatum: "06.06.2025",
  },
  {
    id: 19,
    angebotsnummer: "2025-025",
    auftraggeber: "chen@gmail.com",
    profilbezeichnung: "connective",
    erstelldatum: "07.07.2025",
  },
  {
    id: 20,
    angebotsnummer: "2025-026",
    auftraggeber: "park@gmail.com",
    profilbezeichnung: "profile system",
    erstelldatum: "08.08.2025",
  },
];
